version: "3"
networks:
    craftcamp:
        driver: bridge

services:
    website:
        container_name: craftcamp_website
        build: applications/website
        image: craftcamp/website
        depends_on:
            - mysql
        env_file:
            - craftcamp.env
        volumes:
            - "./volumes/apps:/srv/apps"
            - "./volumes/logs/game:/srv/logs"
        networks:
            - craftcamp

    scheduler:
        container_name: craftcamp_scheduler
        image: citadeltechnologies/scheduler
        networks:
            - craftcamp

    phpmyadmin:
        container_name: craftcamp_phpmyadmin
        image: nazarpc/phpmyadmin
        environment:
            SESSION_TIMEOUT: 86400
        networks:
            - craftcamp
        ports:
            - "8082:80"

    # MYSQL Database
    mysql:
        container_name: craftcamp_mysql
        build: mysql
        image: craftcamp/mysql
        env_file:
            - craftcamp.env
        networks:
            - craftcamp
        ports:
            - "33306:3306"
        volumes:
            # mysql
            - "./volumes/mysql:/var/lib/mysql"

    # Nginx webserver
    nginx:
        container_name: craftcamp_nginx
        build: nginx
        image: craftcamp/nginx
        depends_on:
            - website
        env_file:
            - craftcamp.env
        extra_hosts:
            - "local.craftcamp.fr:127.0.0.1"
            - "release.craftcamp.fr:127.0.0.1"
        volumes:
            # applications
            - "./volumes/apps:/srv/apps"
            # nginx
            - "./volumes/ssl:/etc/letsencrypt"
            - "./volumes/html:/usr/share/nginx/html"
            - "./volumes/logs/nginx:/var/log/nginx"
        networks:
            - craftcamp
        ports:
            - "443:443"
            - "80:80"
